connector_image: airbyte/source-faker:dev
test_strictness_level: high
acceptance_tests:
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
  spec:
    tests:
      - spec_path: source_faker/spec.json
  discovery:
    tests:
      - config_path: secrets/config.json
        backward_compatibility_tests_config:
          disable_for_version: "4.0.0" # We changed the '*_id' and products.year fields to be integers instead of number
  basic_read:
    tests:
      - config_path: secrets/config.json
        client_container_config:
          client_container_dockerfile_path: integration_tests/Dockerfile.cat_setup_teardown
          setup_command:
            ["touch", "/connector/integration_tests/configured_catalog2.json"]
          teardown_command:
            [
              "rm",
              "/connector/integration_tests/configured_catalog2.json",
            ]
        expect_records:
          path: integration_tests/expected_records.jsonl
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        client_container_config:
          client_container_dockerfile_path: integration_tests/Dockerfile.cat_setup_teardown
          setup_command:
            ["touch", "/connector/integration_tests/configured_catalog2.json"]
          teardown_command:
            [
              "rm",
              "/connector/integration_tests/configured_catalog2.json",
            ]
        ignored_fields:
          users:
            - name: updated_at
              bypass_reason: "dynamic field"
            - name: created_at
              bypass_reason: "dynamic field"
          products:
            - name: updated_at
              bypass_reason: "dynamic field"
            - name: created_at
              bypass_reason: "dynamic field"
          purchases:
            - name: updated_at
              bypass_reason: "dynamic field"
            - name: created_at
              bypass_reason: "dynamic field"
  incremental:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        client_container_config:
          client_container_dockerfile_path: integration_tests/Dockerfile.cat_setup_teardown
          setup_command:
            [
              "echo",
              "{}",
              ">>",
              "/connector/integration_tests/abnormal_state2.json",
            ]
          teardown_command:
            [
              "rm",
              "/connector/integration_tests/configured_catalog2.json",
            ]
          between_syncs_command:
            [
              "echo",
              ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> running something!!!!!!!!",
            ]

        future_state:
          future_state_path: integration_tests/abnormal_state.json
